### PR TITLE
Feature/mslt port

### PR DESCRIPTION
**Pull request by robmoss**
Anja and I have checked (double-checked, triple-checked) the MSLT simulation results against the spreadsheet model, and they're now in good agreement. I've also updated the documentation, incorporating feedback from Anja and Tony. Hopefully this is now ready to merge and include in the next VPH release.

### CODE REVIEW

**Comment by robmoss** [comment]
I need to push one more commit, and I'm not sure how to best go about it due to the merge commit (I didn't realise that resolving the conflicts via the web interface would automatically create a merge commit). Apologies for my confusion. Any advice, James?

**Comment by collijk** [comment]
Pull the merge commit into your local repo and resolve any conflicts. then push it back up.

**Comment by collijk** [comment]
Also, we should schedule like a large chunk of time to review this together.

**Comment by robmoss** [comment]
I've pushed the new commit, and yes, it absolutely makes sense to review this together. I'll get in touch via email.

**Comment by collijk** [comment]
Core bits merged in already.

**Pull request closed without merging**
